### ISSUE TITLE
Support requesting SSH keys from gnome-keyring

### ISSUE THREAD

**Issue by nodiscc** [danfruehauf/NetworkManager-ssh#21]
Are gnome-keyring queries supported?

My SSH key is password protected but gnome-keyring has an ssh-agent like that is able to store the key in memory after it's unlocked, and provide the key to applications that request it. I think this is the best way to handle keys (if my key is already unlocked, do not ask for the password once again)

Seahorse and gnome-keyring provide a centralized and secure way to manage my keys and passwords for SSH, GPG, Web browsers (Firefox, Chromium), Instant Messaging (pidgin), Wireless networks (network-manager) and more. As nm-applet uses gnome-keyring for the wireless network passwords, I thought it would be nice to integrate NetworkManager-ssh with it too. It would save some password typing, allow using SSH keys as requested in #13, and provide a safe access to the keys.

[pidgin-gnome-keyring](https://code.google.com/p/pidgin-gnome-keyring/) is written in C and provides access to the keyring for the pidgin instant messaging client. I hope you could borrow some code there.

**Comment by danfruehauf** [comment]
Just updated the link to the pidgin-gnome-keyring project.
