### ISSUE TITLE
cannot find libnma-dev

### ISSUE THREAD

**Issue by BertHartm** [danfruehauf/NetworkManager-ssh#49]
I'm attempting to build on ubuntu wily.
Apt can't seem to resolve libnma-dev , and all my googling for the effort seems to point to the readme here as being the only reference to it.
Any hints as to what it is? It's definitely required as the build won't progress without it (or intltool, which I'll submit a PR for once I get a successful build). It's probably part of another package, I probably need more to search for than the name of the library though.

Actual error from ./configure:
checking for GIO... yes
checking for GTK... yes
checking for LIBNMA... no
configure: error: Package requirements (libnma >= 1.1.0) were not met:

No package 'libnma' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables LIBNMA_CFLAGS
and LIBNMA_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details

**Comment by danfruehauf** [comment]
Thanks for the feedback. What's ubuntu wily? Is that the newest ubuntu?

Changes on master currently correspond to the newest NM that's out there.

I would recommend trying to build from https://github.com/danfruehauf/NetworkManager-ssh/commits/0.9.4 

Either way, I'll try to get an Ubuntu wily VM running and see what happens.

**Comment by BertHartm** [comment]
Yep, wily is ubuntu 15.10

0.9.4 worked, though I had to install libnm-gtk-dev and libsecret-1-dev in addition to the list currently in the readme. Would you prefer a PR that tells people how to build 0.9.4 for wily or wait until you get master working?

Thanks for the help, going to try using it.

**Comment by danfruehauf** [comment]
Better update the doc, why not :)

**Comment by danfruehauf** [comment]
Documentation has libmna-dev, so this is alright.
