### ISSUE TITLE
SSH not showing up in "connection type" dialog

### ISSUE THREAD

**Issue by BertHartm** [danfruehauf/NetworkManager-ssh#50]
I'm on Ubuntu Wily (15.10).
I built 0.9.4 for ubuntu and installed both and installed both network-manager-ssh_0.9.4-0ubuntu_amd64.deb and network-manager-ssh-gnome_0.9.4-0ubuntu_amd64.deb

My /etc/dbus-1/system.d/org.freedesktop.NetworkManager.conf already had a line for <allow send_destination="org.freedesktop.NetworkManager.ssh"/> in <busconfig> for <policy user="root">. I added an entry in <policy context="default"> as well. I've rebooted just for sanity sake.

I can't get an "SSH" option to show up in the "Choose a Connection Type" dialog. Am I missing a step?

**Comment by danfruehauf** [comment]
So the configuration UI supports only the GTK/GNOME applet. I'm just verifying you're not on KDE or something?

The file that will be dynamically loaded and displayed in the UI should be at `/usr/lib/NetworkManager/libnm-ssh-properties.so`. This should be enough to give you the `SSH` option. While the system logs will not tell you if things are OK, I'd still look for errors, just in case.

I've never tested it on Ubuntu 15.10. Let alone I'm not testing it on Ubuntu. I'm still looking for a packager to maintain it properly for debian/Ubuntu. That is, also to maintain the packaging requirements. If that never happens, the best I could do is provide "guidelines" as to how to package it but can never guarantee anything beyond. Sorry about that.

**Comment by BertHartm** [comment]
Thanks, I completely understand that this is a volunteer effort for you and appreciate all the work you've put in to making this. I hope to contribute back in some form or another when I get it working.

I rebuilt and checked on another computer, and the .so file is generated and looks right. Restarting Network Manager generates:
NetworkManager[15125]: <info>  VPN: loaded org.freedesktop.NetworkManager.ssh
in syslog. Don't see any obvious errors in there.

I'm using fairly stock ubuntu, so it should all be fairly stock Gnome I think, no kde. The network-manager-openvpn-gnome package (which is what I'm hoping to replace) works fine. I may go through and try to debug via comparison with that package later on when I have some free time.

**Comment by danfruehauf** [comment]
@BertHartm Thanks for that.

A couple more pointers, this means the ssh module was successfully loaded by nm, however it doesn't necessarily mean that you gonna see that in the applet. Please note that 2 packages are being created. One for the core nm integration and one for the gnome/gtk UI (this is standard for all nm plugins).

Try running also `nm-connection-editor`, which will force loading of the available UI plugins, see if you get any errors there.

BTW, you can also get in touch with me on FreeNode, I'm on the nm channel...

**Comment by danfruehauf** [comment]
Been a while on this one. I'll close it too.
