### ISSUE TITLE
New release version?

### ISSUE THREAD

**Issue by lhw** [danfruehauf/NetworkManager-ssh#52]
I saw that you bumped the version in the repo to 1.1.0  ad64a9f1 for the upcoming changes with libnm. But so far you haven't tagged any commit as new release on Github. Are there still some compatibility issues left with the plugin?

I'd like to upgrade the [debian package](https://packages.qa.debian.org/n/network-manager-ssh.html) in the near future. And it would be handy to use an upstream version. Ubuntu 16.04 will already include the 0.9.4 release either way, removing the need for a ppa (#51).

**Comment by danfruehauf** [comment]
@lhw Oh wow! There is a debian package for that!

I recently received some patches which include adaptations for the nm 1.2.0. I must say I haven't had the chance to test those patches, but I trust them since they came from @lkundrak who is a nm maintainer.

So I'm happy to tag master as 1.1.0 if that is what you're after. Will that be good?

I'm happy to do anything required so packaging is easier, especially for debian.

**Comment by lhw** [comment]
Basically yes, that's what I am after.

I will be doing some test builds with the libnm builds in debian unstable/sid (1.1.91) and if everything works I'd push 1.1.0 to unstable. But it will probably not be merged into Ubuntu for 16.04 so close to release.

**Comment by danfruehauf** [comment]
That's fine. I was ever looking for someone to package it for debian/ubuntu. It's amazing.

So apart from tagging master as 1.1.0, what else can I do for you?

**Comment by danfruehauf** [comment]
@lhw https://github.com/danfruehauf/NetworkManager-ssh/tree/1.1.0

:beers:

**Comment by lhw** [comment]
Thanks for adding the new version. I already got it packaged. But I need to do some testing before I upload it to unstable. A bit busy right now.

Otherwise you already provided most of the files I needed for the package. I really only needed to change minor things from your debian/ directory. Actually I could just do a pull request for the changes and we could change the Vcs links to this repository if you are interested in that.

**Comment by lkundrak** [comment]
So, uhm; sorry for chiming in this late. I've aligned the versioning with NetworkManager where the odd releases mean "development" and even numbers are releases.

The master code now targets NetworkManager 1.2, and only builds and works works with a 1.2 snapshot. See ad64a9f12a062781582037a71f56365e4fdc659e for details.

Therefore, with NetworkManager 1.2 a version 1.2 should be released. 1.1.0 shouldn't really have been tagged as it doesn't work with latest released NetworkManager 1.0.0; but I guess we can't do much about that now. Sorry for not speaking up earlier.

**Comment by lhw** [comment]
It's not uploaded yet. I can still tag it however its supposed to be 
versioned. My current git tags are just for myself until I upload it to 
unstable.
Current nm builds in debian unstable are 1.1.91 will this create an issue?

**Comment by danfruehauf** [comment]
> Otherwise you already provided most of the files I needed for the package. I really only needed to change minor things from your debian/ directory. Actually I could just do a pull request for the changes and we could change the Vcs links to this repository if you are interested in that.

I actually prefer those debian files to be out of this repository, keeping code only. I'll probably remove also the spec file. It was meant to be there only for convenience. Now that it is maintained in distributions, it's probably time to remove those things. What do you think @lhw @lkundrak?

**Comment by danfruehauf** [comment]
> The master code now targets NetworkManager 1.2, and only builds and works works with a 1.2 snapshot. See ad64a9f for details.

@lkundrak I would generally like to align the version with upstream nm plugins - if that makes sense. As you realized, I'm all about making this project as much "mainstream" as possible. I know the ecosystem of the nm plugins is already quite diverse - the last thing I want to do is make it more difficult for anyone.

Or in short, please feel free to provide advice as to what you think should happen with that plugin (i.e. move to cgit like the rest of the plugins etc).

**Comment by lhw** [comment]
> I actually prefer those debian files to be out of this repository, keeping code only. I'll probably remove also the spec file. It was meant to be there only for convenience. Now that it is maintained in distributions, it's probably time to remove those things. What do you think @lhw @lkundrak?

I don't really need them to be in the repository. The actual repository I am building from is maintained via the collab-maint git: http://anonscm.debian.org/cgit/collab-maint/network-manager-ssh.git
So if you don't want the debian/ dir repository that is fine. But I noticed that the debian/changelog unlike the /ChangeLog actually has some information until 0.9.3. You might want to move and keep the file.

When you have decided on a version I can do the upload. Did some testing yesterday with the version currently tagged as 1.1.0 and it seemed to work fine.

**Comment by danfruehauf** [comment]
I must say I got a bit lost with the versions of things. @lkundrak I'll try and catch you on IRC in the next few days for a quick chat if that's OK. I'll try to understand a bit better how to manage this project (and myself) :)

**Comment by danfruehauf** [comment]
I think I've been better with versioning and tags, so I'll close this one. @lhw please reopen if you believe something it still missing in the process.
