### ISSUE TITLE
Timed out waiting for the service

### ISSUE THREAD

**Issue by alxchk** [danfruehauf/NetworkManager-ssh#57]
I'm trying to use nm-ssh with nm from git on gentoo. 
Builld was successful. Also I edited dbus config. In log I have just this:
```
NetworkManager[1275517]: <info>  [1467538466.3580] audit: op="connection-activate" uuid="9846d23c-b4e4-49dd-b76c-2fe50b27a7e4" name="10.2.2.0" pid=498863 uid=1000 result="success"
NetworkManager[1275517]: <info>  [1467538466.3622] vpn-connection[0x5619dceb7400,9846d23c-b4e4-49dd-b76c-2fe50b27a7e4,"10.2.2.0",0]: Started the VPN service, PID 1275934
NetworkManager[1275517]: <warn>  [1467538471.2649] vpn-connection[0x5619dceb7400,9846d23c-b4e4-49dd-b76c-2fe50b27a7e4,"10.2.2.0",0]: Timed out waiting for the service to start
```
Then I kill running nm-ssh-service and start one manually with  --debug key
``` 
# /usr/libexec/nm-ssh-service --debug
** Message: nm-ssh-service (version 1.2.0) starting...
```

There is no messages. So looks like some problem with communication (dbus?)
What you can suggest to check?

**Comment by danfruehauf** [comment]
G'day. Lets start from the beginning. What version of NetworkManager you're running? What branch did you build from?

Second, after starting `nm-ssh-service --debug`, did you start your VPN? (e.g. `nmcli ...`)

Looking around dbus is probably the right thing, it might stem from wrong permissions for the NetworkManager-ssh plugin, but you said you've edited the config. Did you also restart the service that is responsible for using that config (dbus potentially)?

**Comment by alxchk** [comment]
1. Master: 5b4581b361af47b5d8da7c47cd21265894ad62b2
2. Yes
3. I didn't, but I have this in logs:
```
dbus[698]: [system] Reloaded configuration
dbus[698]: [system] Reloaded configuration
dbus[698]: [system] Reloaded configuration
dbus[698]: [system] Reloaded configuration
dbus[698]: [system] Reloaded configuration
dbus[698]: [system] Reloaded configuration
dbus[698]: [system] Reloaded configuration
dbus[698]: [system] Reloaded configuration
dbus[698]: [system] Reloaded configuration
dbus[698]: [system] Reloaded configuration
```

**Comment by danfruehauf** [comment]
@alxchk Any output from nmcli? Because if the service is up, and you initiate a connection, it must spew some log out. Or else nmcli might complain that it cannot connect to the service (and the service is started).

Either way, if you're using gentoo, you might have the new nm version, which I think I'm aware of it doesn't work with the current version of nm-ssh. I should be looking into that in the next few days.

**Comment by danfruehauf** [comment]
@alxchk I manage to reproduce it on Fedora 24. I'm working on it. There's also an open bug for that on Fedora 24.

**Comment by danfruehauf** [comment]
@lkundrak Your help will be appreciated here. As said, I managed to reproduce it on Fedora 24 (like in https://bugzilla.redhat.com/show_bug.cgi?id=1350244).

**Comment by lkundrak** [comment]
Uh, the service is not getting a bus name as it's not getting initialized. I omitted this when doing the libnm port; sorry for that. Opened the pull request #58 with a fix.
