### ISSUE TITLE
DNS leakage for default route VPNs

### ISSUE THREAD

**Issue by paulswanson** [danfruehauf/NetworkManager-ssh#62]
I'm using NetworkManager-ssh to manage a VPN connection as the default route, i.e. Internet access, with specific and trusted DNS servers for all name resolution when the VPN is connected.

What I'm noticing is that when the SSH VPN is brought up the DNS server entries are merely **appended** to the list of available DNS resolvers (and configured for name resolution on the VPN subnet).

The problem is that default routing over a VPN is a different use case than accessing a private network in some ways. Rather than adding to list of available resolvers, I want the new DNS configuration to replace any existing DNS server list, such as from the underlying network device on an untrusted network.

As such, I'd argue that when the option "Use this connection only for resources on its network" is unticked that VPN DNS server entries should **replace** any preexisting DNS server entries from the underlying network device.

Thanks in advance.

**Comment by danfruehauf** [comment]
@paulswanson G'day!

So I think this is more related to the way that NetworkManager is handling things. nm-ssh is not responsible to do those things. I'd advise to potentially open that bug upstream with NetworkManager. Please verify this behaviour also happens with other types of VPN. If it does - I will stand corrected.

**Comment by Zrubi** [comment]
I can confirm it is a general NetworkManager issue.

**Comment by danfruehauf** [comment]
@Zrubi I'll take your word for it.
