### ISSUE TITLE
How to setup on Kubuntu?

### ISSUE THREAD

**Issue by cibban** [danfruehauf/NetworkManager-ssh#64]
I have the network-manager-ssh installed and can setup SHH VPN in the NetworkManager. I'm just confused as to what address to put where, what netmask to use etc, and Google has failed me.

My LAN is on 192.168.1.* with 192.168.1.1 as gateway.
My SSH server is an AWS ec2 instance with external IP 52.18.141.x.
My SSH server thinks it's on 172.31.24.x (this is what ifconfig shows) with netmask 255.255.240.0.

Tunneling is allowed on the server and I used the iptables example for tun in the README.

Using ssh -D in terminal works fine.

**Comment by danfruehauf** [comment]
So hope this helps, you probably want the following:
 * Gateway: 52.18.141.x.
 * Remote IP: 172.31.24.1 (or use the default)
 * Local IP: 172.31.24.2 (or use the default)
 * Netmask: 255.255.255.252 (default), must make sure that with this netmask both remote IP and local IP can communicate with each other.

This will connect to your EC2 instance on 52.18.141.x. Then create a tun0 interface on the EC2 side with IP address 172.31.24.1 and a tun0 interface on your side with 172.31.24.2. Both netmasks will be 255.255.255.252. If you are going to use this as a gateway, then all traffic will be routed through 172.31.24.2 -> 172.31.24.1 -> 52.18.141.x (I'm being simplistic here).

Hope this helps and please let me know how you go!

**Comment by cibban** [comment]
That didn't work, but it timed out instead of failing directly. Improvement, I guess. :)

What would be the default values for remote and local IP? I tried the ones you wrote and also 10.0.0.1 and 10.0.0.2, in case the 172.31... ones were used on the remote network already.

**Comment by danfruehauf** [comment]
> in case the 172.31... ones were used on the remote network already.

You can easily find out if they are used (just `ifconfig`). The idea for remote IP and local IP is to just use something that's not already in use on either end. Then set a netmask that allow remote IP and local IP to be on the same network. Good luck and let me know how it went :)

**Comment by danfruehauf** [comment]
I'll close this one as I haven't heard anything from the OP for roughly a year.
