### ISSUE TITLE
Connection Failure on Arch

### ISSUE THREAD

**Issue by xavier83** [danfruehauf/NetworkManager-ssh#68]
I got the following journal log when trying to connect using NetworkManager-ssh.
I am using kde-plasma on archlinux with [NetworkManager-ssh](https://aur.archlinux.org/packages/networkmanager-ssh-git) install
```
Error getting ssh-agent socket ownership: 14
Using root's .ssh/known_hosts
-o
ServerAliveInterval=10
-o
TCPKeepAlive=yes
ssh started with pid 6888
[44B blob data]
[56B blob data]
.
.
.
[31B blob data]
ssh exited with error code 255
```

**Comment by danfruehauf** [comment]
I never tested it on archlinux. In fact I'm very unfamiliar with archlinux.

I'll have to look at the code to understand that this *might* actually mean. I'll report my findings here shortly, and hopefully try and go for a fix.

**Comment by danfruehauf** [comment]
@xavier83 It'll be not very easy to debug it, but we should definitely give it a go.

I'll explain first what happens:
 * SSH agent socket (authentication socket) is passed to the nm-ssh-service when you initiate a connection (with your non-privileged user)
 * nm-ssh-service is run with root credentials. It tries to find what is the original user name you initiated the connection with
 * That is to find what is your known_hosts file in your home directory and pass it to ssh

When trying to "guess" your username, nm-ssh-service clearly hits an error. I've never run this on arch linux, but perhaps a full debug dump (see README.md to understand how to provide one) can be useful. Then we can see what is the SSH agent socket and speculate why it can't get its ownership.

I think that regardless, if that fails, nm-ssh-service should use root's known_hosts file. I'll probably amend it soon.

**Comment by arshesney** [comment]
I encountered the same error, if you never connected to the host as root, the service gets stuck at the accept key prompt which appears (only?) when you are running it in debug mode.
After accepting the key the firts time the vpn works.

**Comment by danfruehauf** [comment]
> I encountered the same error, if you never connected to the host as root, the service gets stuck at the accept key prompt which appears (only?) when you are running it in debug mode.
> After accepting the key the firts time the vpn works.

I should probably document that you need to accept the host key before the VPN can actually succeed. It can be overwritten by specifying in the options. So running:
```
$ ssh root@YOUR_HOST
<ACCEPT KEY>
```

This is probably required. I'll amend the README shortly.

**Comment by danfruehauf** [comment]
Hopefully f80495e makes things a bit clearer. @arshesney @xavier83 ?

**Comment by arshesney** [comment]
Oh ya, that definitely makes it clear.

**Comment by danfruehauf** [comment]
To be honest, I kind of assumed that you would try to `ssh root@TARGET_HOST`, even to just configure things. Or at least `ssh someuser@TARGET_HOST` to configure it. But it's better to be explicit and say what's required. So thanks for the feedback!

**Comment by xavier83** [comment]
Ok, seem like the issue is not on NetworkManager-ssh but wrong configuration. apparently if you use someuser@TARGET_HOST , the host is probably rejecting the tun request as it requires root(equivalent?) permission to create tun device.

**Comment by danfruehauf** [comment]
> Ok, seem like the issue is not on NetworkManager-ssh but wrong configuration. apparently if you use someuser@TARGET_HOST , the host is probably rejecting the tun request as it requires root(equivalent?) permission to create tun device.

Unfortunately yes. I think it's possible without using root, but kind of tricky. I was looking into openssh at the time - thinking it can be done easily, but generally to open new devices (tun/tap) you'll need 0 uid privileges, so I just let it go at the time.
